# Generated by Django 5.1.15 on 2026-06-27 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('scale', 'Scale')], max_length=20)),
                ('razorpay_subscription_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_plan_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authenticated', 'Authenticated'), ('active', 'Active'), ('paused', 'Paused'), ('halted', 'Halted'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_subscription_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(max_length=50)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment_records',
                'indexes': [models.Index(fields=['tenant', 'captured_at'], name='payment_rec_tenant__962fb3_idx')],
            },
        ),
    ]
